<?php

/**
 * @file
 * Module file for the Media Asset module.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Url;
use Drupal\Component\Utility\UrlHelper;
use Drupal\media\MediaForm;
use Drupal\media\MediaInterface;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function damopen_assets_form_views_exposed_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  if ($form['#id'] === 'views-exposed-form-asset-search-asset-search') {
    hide($form['type']);
    $current_user = Drupal::currentUser()->id();
    $userStorage = Drupal::entityTypeManager()->getStorage('user');
    /** @var \Drupal\user\UserInterface $user */
    $user = $userStorage->load($current_user);
    if (!$user->hasRole('manager')) {
      hide($form['status']);
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function damopen_assets_preprocess_views_view__asset_search(array &$variables) {
  /** @var \Drupal\damopen_assets\HelperInterface $helper */
  $helper = \Drupal::service('damopen_assets.helper');
  // We select the first from bundles.
  $type = $helper->requestToType(Drupal::request());

  if (!in_array($type, ['', 'image'], TRUE)) {
    // @todo: This might not be the best approach.
    // But it seems to be working!
    unset($variables['exposed']);
  }

  $variables['media_description'] = $helper->usageGuideMarkup($type);
}

/**
 * Implements hook_preprocess_page().
 */
function damopen_assets_preprocess_page(array &$variables) {
  $routeMatch = Drupal::routeMatch();
  $routeName = $routeMatch->getRouteName();

  if ($routeName !== 'entity.media.add_page') {
    /** @var \Drupal\damopen_assets\HelperInterface $hepler */
    $hepler = \Drupal::service('damopen_assets.helper');
    $type = $hepler->requestToType(Drupal::request());
    $variables['media_description'] = $hepler->usageGuideMarkup($type);
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function damopen_assets_preprocess_html(array &$variables) {
  $routeMatch = Drupal::routeMatch();
  $routeName = $routeMatch->getRouteName();
  switch ($routeName) {
    case 'entity.media.canonical':
      $variables['attributes']['class'][] = 'media--view';
      break;

    case 'entity.media.edit_form':
      $variables['attributes']['class'][] = 'media--edit';
      break;

    case 'entity.media.add_form':
      $variables['attributes']['class'][] = 'media--add';
      break;
  }

  if (\Drupal::service('damopen_assets.helper')
      ->requestToType(Drupal::request()) !== 'image') {
    $variables['attributes']['class'][] = 'no-filter';
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function damopen_assets_media_presave(MediaInterface $media) {
  $currentUser = Drupal::currentUser();
  $owner = ($media->getOwner()->id() === $currentUser->id()) ? 'own' : 'any';
  if (!$currentUser->hasPermission("publish own media")
    && !$currentUser->hasPermission("publish any media")) {
    $media->set('status', FALSE);
  }

  // If the user doesn't add an alt text for the image,
  // autofill from asset name.
  if ($media->bundle() === 'image') {
    /** @var \Drupal\image\Plugin\Field\FieldType\ImageItem $item */
    foreach ($media->get('field_image') as $index => $item) {
      if (empty(trim($item->get('alt')->getString()))) {
        $item->set('alt', $media->getName());
      }
    }
  }

  // For youtube videos, we only need the video ID.
  if ($media->bundle() === 'video') {
    $video_url = UrlHelper::parse($media->get('field_video')->getString());
    if (preg_match('/youtube\.com/', $video_url['path'])) {
      $video_url['query'] = [
        'v' => $video_url['query']['v'],
      ];
      $new_url = Url::fromUri($video_url['path'], $video_url);
      $media->set('field_video', $new_url->toString());
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function damopen_assets_form_media_type_edit_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\Core\Entity\EntityFormInterface $formObject */
  $formObject = $form_state->getFormObject();
  /** @var \Drupal\media\MediaTypeInterface $mediaType */
  $mediaType = $formObject->getEntity();

  // DAM-100 | enable HTML formatting.
  $form['description'] = [
    '#title' => t('Description'),
    '#type' => 'text_format',
    '#default_value' => $mediaType->getDescription(),
    '#description' => t('Describe this media bundle. The text will be displayed on the <em>Add new content</em> page.'),
    '#weight' => -80,
  ];

  // Add submit handler to set the Description.
  $form['actions']['submit']['#submit'] = array_merge(['damopen_assets_form_media_type_edit_form_submit'], $form['actions']['submit']['#submit']);
}

/**
 * Form submission handler for media_type_edit_form().
 *
 * @see damopen_assets_form_media_bundle_edit_form_alter()
 */
function damopen_assets_form_media_type_edit_form_submit(array $form, FormStateInterface $form_state) {
  $form_state->setValue('description', $form['description']['value']['#value']);
}

/**
 * Implements hook_views_pre_view().
 */
function damopen_assets_views_pre_view(ViewExecutable $view, $display_id, array &$args) {
  if ($display_id === 'asset_search' && $view->id() === 'asset_search') {
    $filters = $view->getExposedInput();
    if (empty($filters['type'])) {
      $filters['type'] = 'image';
      $view->setExposedInput($filters);
    }
  }
}

/**
 * Implements hook_views_post_render().
 */
function damopen_assets_views_post_render(ViewExecutable $view) {
  // Replace the page title for asset_search view.
  if ($view->id() === 'asset_search') {
    $title = $view->getTitle();
    $filters = $view->getExposedInput();
    if ($filters['type'] === 'video video_file') {
      $title = 'Video files & embeds';
    }
    else {
      /** @var \Drupal\media\MediaTypeInterface $mediaType */
      $mediaType = Drupal::entityTypeManager()
        ->getStorage('media_type')
        ->load($filters['type']);
      if ($mediaType !== NULL) {
        // @todo: Drupal 8.9 should allow plurals on bundle labels.
        // @see: https://www.drupal.org/project/drupal/issues/2765065
        $title = "{$mediaType->label()}s";
      }
    }

    // Set the view title.
    $view->setTitle($title);
    // Set the route title.
    /** @var \Symfony\Component\Routing\Route $route */
    $route = Drupal::routeMatch()->getCurrentRouteMatch()->getRouteObject();
    $route->setDefault('_title', $title);
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function damopen_assets_preprocess_entity_add_list(array &$variables) {
  \Drupal::service('damopen_assets.helper')->entityAddList($variables);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function damopen_assets_preprocess_media(array &$variables) {
  /* @todo:
   * Find a better way, e.g specifying a custom thumbnail field from config
   * on the UI.
   */
  /** @var \Drupal\media\MediaInterface $media */
  $media = $variables['media'];

  if (
    $media->hasField('thumbnail')
    && $media->hasField('field_custom_thumbnail')
  ) {
    $thumbField = $media->get('thumbnail');
    $customThumbField = $media->get('field_custom_thumbnail');

    /** @var \Drupal\file\FileInterface $thumbFile */
    if (
      isset($variables['content']['thumbnail'], $variables['content']['field_custom_thumbnail'])
      && !$customThumbField->isEmpty()
      && !$thumbField->isEmpty()
      && ($thumbFile = $media->get('thumbnail')->entity)
      && strpos($thumbFile->getFileUri(), 'media-icons/generic') !== FALSE
    ) {
      $variables['content']['thumbnail'] = $variables['content']['field_custom_thumbnail'];
      unset($variables['content']['field_custom_thumbnail']);
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_view_alter().
 */
function damopen_assets_media_view_alter(array &$build, MediaInterface $media, EntityViewDisplayInterface $display) {
  // @todo: Find a better way.
  $bundle = $media->bundle();
  // Image is handled entirely differently.
  if ($build['#view_mode'] !== 'full' || $bundle === 'image') {
    return;
  }

  $specialBundles = [
    'audio',
    'video',
    'video_file',
  ];

  $build['asset_preview'] = [];

  /** @var \Drupal\damopen_assets\HelperInterface $helper */
  $helper = \Drupal::service('damopen_assets.helper');

  if (!in_array($bundle, $specialBundles, TRUE)) {
    // @todo: Get this from the default view, don't hardcode.
    $displayOptions = [
      'type' => 'image',
      'weight' => '10',
      'label' => 'hidden',
      'settings' => [
        'image_style' => 'crop_thumbnail',
        'image_link' => '',
      ],
      'third_party_settings' => [],
      'region' => 'content',
    ];

    if ($preview = $helper->generateFieldView($media, 'field_custom_thumbnail', $displayOptions)) {
      $build['asset_preview'] = $preview;
    }
    elseif ($preview = $helper->generateFieldView($media, 'thumbnail', $displayOptions)) {
      $build['asset_preview'] = $preview;
    }
  }
  elseif ($bundle === 'video') {
    // @todo: Get this from the default view, don't hardcode.
    $displayOptions = [
      'type' => 'video_embed_field_video',
      'weight' => '1',
      'label' => 'hidden',
      'settings' => [
        'responsive' => 'true',
        'width' => '854',
        'height' => '480',
        'autoplay' => 'false',
      ],
      'third_party_settings' => [],
      'region' => 'content',
    ];

    if ($preview = $helper->generateFieldView($media, 'field_video', $displayOptions)) {
      $build['asset_preview'] = $preview;
    }
  }
  elseif ($bundle === 'video_file') {
    // @todo: Get this from the default view, don't hardcode.
    $displayOptions = [
      'type' => 'file_video',
      'weight' => '1',
      'label' => 'hidden',
      'settings' => [
        'controls' => TRUE,
        'multiple_file_display_type' => 'tags',
        'width' => 640,
        'height' => 480,
        'autoplay' => FALSE,
        'loop' => FALSE,
        'muted' => FALSE,
      ],
      'third_party_settings' => [],
      'region' => 'content',
    ];

    if ($preview = $helper->generateFieldView($media, 'field_video_file', $displayOptions)) {
      $build['asset_preview'] = $preview;
    }
  }
  elseif ($bundle === 'audio') {
    // @todo: Get this from the default view, don't hardcode.
    $displayOptions = [
      'type' => 'file_audio',
      'weight' => '1',
      'label' => 'hidden',
      'settings' => [
        'controls' => TRUE,
        'multiple_file_display_type' => 'tags',
        'autoplay' => FALSE,
        'loop' => FALSE,
      ],
      'third_party_settings' => [],
      'region' => 'content',
    ];

    if ($preview = $helper->generateFieldView($media, 'field_file', $displayOptions)) {
      $build['asset_preview'] = $preview;
    }
  }
}

/**
 * Implements hook_menu_local_actions_alter().
 */
function damopen_assets_menu_local_actions_alter(array &$actions) {
  unset($actions['media_upload.bulk_media_upload_list']);
}

/**
 * Implements hook_menu_links_discovered_alter().
 */
function damopen_assets_menu_links_discovered_alter(array &$links) {
  unset($links['media_upload.bulk_media_upload_list']);
}

/**
 * Implements hook_form_alter().
 */
function damopen_assets_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\media\MediaForm $form_object */
  $form_object = $form_state->getFormObject();

  if (
    isset($form['revision_information'])
    && get_class($form_object) === MediaForm::class
    && $form_object->getOperation() === 'add'
  ) {
    $form['revision_information']['#open'] = FALSE;
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function damopen_assets_preprocess_menu_local_tasks(&$variables) {
  \Drupal::service('damopen_assets.helper')->menuLocalTasks($variables);
}

/**
 * Implements hook_jsonapi_entity_filter_access().
 */
function damopen_assets_jsonapi_entity_filter_access(EntityTypeInterface $entity_type, AccountInterface $account) {
  return ([
    JSONAPI_FILTER_AMONG_ALL => AccessResult::allowedIfHasPermission($account, 'access media asset to approval'),
  ]);
}
