<?php

/**
 * Install file for media_collection.
 */

use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\StringTranslation\TranslatableMarkup;

/**
 * Install "Assets archive" field for media collections.
 */
function media_collection_update_8701() {
  $updateManager = Drupal::entityDefinitionUpdateManager();

  $definition = BaseFieldDefinition::create('file')
    ->setCardinality(1)
    ->setLabel(new TranslatableMarkup('Archived assets'))
    ->setDescription(new TranslatableMarkup('Field holding the download file for all assets'))
    ->setSetting('file_extensions', 'zip')
    ->setSetting('uri_scheme', 'private')
    ->setSetting(
      'file_directory',
      'collection/standard/[date:custom:Y]-[date:custom:m]-[date:custom:d]/[media_collection:uuid]'
    )
    ->setDisplayOptions('view', [
      'label' => 'hidden',
      'type' => 'file_url_plain',
      'weight' => 0,
    ])
    ->setDisplayConfigurable('form', TRUE)
    ->setDisplayConfigurable('view', TRUE)
    ->setRevisionable(TRUE);

  $updateManager->installFieldStorageDefinition(
    'assets_archive',
    'media_collection',
    'media_collection',
    $definition
  );
}

/**
 * Install "Shared with" field for media collections.
 */
function media_collection_update_10000() {
  $updateManager = Drupal::entityDefinitionUpdateManager();

  $definition = BaseFieldDefinition::create('entity_reference')
    ->setLabel(new TranslatableMarkup('Shared with'))
    ->setDescription(new TranslatableMarkup('Users with whom this collection is shared.'))
    ->setSetting('target_type', 'user')
    ->setSetting('handler', 'default')
    ->setCardinality(-1)
    ->setDisplayOptions('view', [
      'label' => 'hidden',
      'type' => 'author',
      'weight' => 0,
    ])
    ->setDisplayOptions('form', [
      'type' => 'entity_reference_autocomplete',
      'weight' => 5,
      'settings' => [
        'match_operator' => 'CONTAINS',
        'size' => '60',
        'autocomplete_type' => 'tags',
        'placeholder' => '',
      ],
    ])
    ->setDisplayConfigurable('form', TRUE)
    ->setDisplayConfigurable('view', TRUE);

  $updateManager->installFieldStorageDefinition(
    'shared_with',
    'media_collection',
    'media_collection',
    $definition
  );
}
