<?php

/**
 * Implements hook_theme().
 */
function damopen_common_theme() {
  return [
    'damopen_common_header_menu' => [
      'variables' => [
        'menu' => [],
      ],
    ],
    'damopen_common_edit_menu' => [
      'variables' => [
        'content' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_page_attachments_alter().
 */
function damopen_common_page_attachments_alter(&$page){
  $page['#attached']['library'][] = 'core/drupal.ajax';
}
