<?php

use Drupal\Core\Cache\Cache;

/**
 * Implements hook_theme().
 */
function damo_extended_collection_theme($existing, $type, $theme, $path) {
  return [
    'create_collection' => [
      'variables' => [
        'url' => NULL,
      ],
    ],
    'add_to_collection' => [
      'variables' => [
        'collections' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_page().
 */
function damo_extended_collection_preprocess_page(&$variables) {
  // Get current media.
  // $media = \Drupal::routeMatch()->getParameter('media');
  // Invalidate media cache tags.
  // $cache_tags = $media->getCacheTags();
  // Cache::invalidateTags($cache_tags);
}
